name: 'Unit Tests'
on:
  pull_request:
    branches:
      - 'main'
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.402'
      - name: Restore
        run: dotnet workload restore
      - name: Build
        run: dotnet build -f net7.0
      - name: Test
        run: dotnet test -f net7.0